### PR TITLE
Error handling for Rust and Python

### LINKED ISSUE #20: Return Result instead of Option in Capsule::open_reencrypted()?
`Capsule::open_reencrypted()` can fail in several different ways:
- an empty cfrag list is provided
- mismatched cfrags (different precursors)
- mismatched capsule (internal verification fails)
- two polynomial coefficients equal to each other (very rare, or someone tampered with the input)
- digest of the secret value `d` is zero (very rare, or someone tampered with the input)

For all of this `None` is returned. Do we want to differentiate between these errors?

### LINKED ISSUE #31: Error handling in Python bindings
Right now there's no real error handling for return values - perhaps we should raise exceptions instead of returning `None`.

Also some input type checking would be great. ~~For example, it is possible to supply a list of integers in place of a `&[u8]` without any complaint from the bindings.~~ Actually, no, the bindings check for the `bytes` type. No problem here.

### PR DESCRIPTION
**Pull request by fjarri**
Based on top of #41
Fixes #20 
Fixes #31

- returning `Result` instead of `Option` in Rust methods
- raising corresponding Python exceptions in Python bindings
- implemented `__eq__()`, `__hash__()` and `__repr__()` too where appropriate (using the new `HasSerializableBackend` helper)
- update Python and Rust docs, and Python type annotations

### CODE REVIEW

File: umbral-pre-python/src/lib.rs [hunk 1]
```diff
@@ -15,63 +108,222 @@ impl SecretKey {
...
     #[staticmethod]
-    pub fn from_secret_key(sk: &SecretKey) -> Self {
+    pub fn random() -> Self {
         Self {
-            backend: umbral_pre::PublicKey::from_secret_key(&sk.backend),
+            backend: umbral_pre::SecretKeyFactory::random(),
         }
     }
+
+    pub fn secret_key_by_label(&self, label: &[u8]) -> PyResult<SecretKey> {
```
Comment (piotr-roslaniec) [inline umbral-pre-python/src/lib.rs:162]: Nitpick: Maybe we could have `from_label` here, similar to `PublicKey.from_secret_key`?

File: umbral-pre-python/src/lib.rs [hunk 2]
```diff
@@ -177,28 +506,50 @@ pub fn decrypt_reencrypted(
...
+fn _umbral(py: Python, m: &PyModule) -> PyResult<()> {
     m.add_class::<SecretKey>()?;
+    m.add_class::<SecretKeyFactory>()?;
     m.add_class::<PublicKey>()?;
-    m.add_class::<Parameters>()?;
+    m.add_class::<Capsule>()?;
+    m.add_class::<KeyFrag>()?;
+    m.add_class::<CapsuleFrag>()?;
+    m.add("GenericError", py.get_type::<GenericError>())?;
     m.add_function(wrap_pyfunction!(encrypt, m)?).unwrap();
```
Comment (piotr-roslaniec) [inline umbral-pre-python/src/lib.rs:553]: Can we also `?` instead of `unwrap()` other calls here?

Comment (fjarri) [reply umbral-pre-python/src/lib.rs:553]: Good point. I took this bit directly from the manual, who know why they put `unwrap()` there.

File: umbral-pre-python/docs/index.rst [hunk 3]
```diff
@@ -77,14 +113,38 @@ API reference
 
         Verifies the integrity of the fragment using the signing key and, optionally, the delegating and the receiving keys (if they were included in the signature in :py:func:`generate_kfrags`).
 
+    .. py:method:: __bytes__() -> bytes
```
Comment (KPrasch) [inline umbral-pre-python/docs/index.rst:116]: I notice GH is drawing a red box around `->`.  Is this some kind of special character?
Screenshot from 2021-04-21 09-52-13

Comment (fjarri) [reply umbral-pre-python/docs/index.rst:116]: I think it's just not used to explicit typehints in the docs. I have to put them in since I have no actual sources, and Sphinx doesn't seem to be able to parse `.pyi`.

Although I'm now thinking that a better approach would be to write a thin wrapper over the Rust bindings. This way:
- docs and typehints will all be in one place and won't need to be repeated
- we can create a more Pythonic API with optional parameters, which are not supported in Rust

File: umbral-pre-python/src/lib.rs (hunk 2 above)
Comment (fjarri) [reply umbral-pre-python/src/lib.rs]: Fixed this in #41

File: umbral-pre/src/key_frag.rs [hunk 4]
```diff
@@ -249,63 +233,67 @@ impl KeyFrag {
...
-            .chain_bool(self.proof.delegating_key_signed)
-            .chain_bool(self.proof.receiving_key_signed);
-        if self.proof.delegating_key_signed {
-            // `delegating_pk` is guaranteed to be Some here.
-            digest = digest.chain_pubkey(&delegating_pk.unwrap());
+        if commitment != &u * &key {
+            return false;
+        }
+
+        // A shortcut, perhaps not necessary
```
Comment (piotr-roslaniec) [inline umbral-pre/src/key_frag.rs:240]: For me personally, it was easier to understand what is being passed to `hash_to_cfrag_signature` without those early returns - `none_unless` describes the relationship between `maybe_*_pk` and `self.proof.*_key_signed` very clearly.

**Review by piotr-roslaniec — APPROVED** [review]
LGTM :+1:

File: umbral-pre/src/key_frag.rs (hunk 4 above)
Comment (fjarri) [reply umbral-pre/src/key_frag.rs:240]: In #47 these returns will return specific errors (and raise exceptions in Python's case), to help user pinpoint the cause of verification failure.

File: umbral-pre-python/src/lib.rs [hunk 5]
```diff
@@ -42,6 +42,27 @@ fn from_bytes<T: HasSerializableBackend<U>, U: SerializableToArray>(bytes: &[u8]
...
+    Python::with_gil(|py| {
+        let builtins = PyModule::import(py, "builtins")?;
+        let arg1 = PyUnicode::new(py, T::name());
+        let arg2: PyObject = PyBytes::new(py, serialized.as_slice()).into();
+        builtins.getattr("hash")?.call1(((arg1, arg2),))?.extract()
+    })
+}
+
+// For some reason this lint is not recognized in Rust 1.46 (the one in CI)
+// remove when CI is updated to a newer Rust version.
```
Comment (cygnusv) [inline umbral-pre-python/src/lib.rs:65]: What about updating rust in the CI config?

**Review by cygnusv — APPROVED** [review]

File: umbral-pre-python/src/lib.rs (hunk 5 above)
Comment (fjarri) [reply umbral-pre-python/src/lib.rs:65]: It is actually run on both Rust 1.46 (minimum supported Rust version, MSRV) and the current stable version. 1.46 was chosen because it's the MSRV of the Rust-Crypto stack. We could bump MSRV, but I wouldn't want to do that just because of a single lint.

File: umbral-pre-python/docs/index.rst (hunk 3 above)
Comment (fjarri) [reply umbral-pre-python/docs/index.rst:116]: Added a comment to #30
